### ISSUE TITLE
Wiki gone?

### ISSUE THREAD

**Issue by junminleeKS** [instacart/truetime-android#106]
Hello,
I apologize if this is not the place to be submitting such issues but I am unable to see the wiki for this repo. All of the hyperlinks re-direct to the home page.

**Comment by thiagotalma** [comment]
@kaushikgopal 
@instacart-devops

**Comment by thuypt** [comment]
@junminleeKS Do you mean this https://github.com/instacart/truetime-android/wiki/How-to-use-this-library ? Seem works.

**Comment by junminleeKS** [comment]
There it is! :D
