### ISSUE TITLE
convert to Kotlin

### ISSUE THREAD

**Issue by kaushikgopal** [instacart/truetime-android#113]
Instacart is deeply committed to Kotlin. Also we've noticed that having the code base would just encourage more folks to be on top of the library.

Throwing this in here, to gauge feedback. We'd probably keep a tag for posterity in case there are folks who strongly prefer to keep the java version

**Comment by fahadayaz** [comment]
Coroutine support would be great :)

**Comment by kaushikgopal** [comment]
we just merged 4.0.0.alpha. Kotlin + coroutines 💪🏽
