### ISSUE TITLE
Fail to initialize Rx library may not be communicated to API consumer

### ISSUE THREAD

**Issue by sebaslogen** [instacart/truetime-android#17]
In the Rx version, I understand the errors to get the time from the server are transformed into `null` Date objects and then [emitted](https://github.com/instacart/truetime-android/blob/master/library-extension-rx/src/main/java/com/instacart/library/truetime/extensionrx/TrueTimeRx.java#L67).
In case all requests fail immediately (no back-off mechanism), for example when there is a short unavailability of internet connection during initialization, then the observable will complete with 0 items emitted thanks to the [filter for nulls](https://github.com/instacart/truetime-android/blob/master/library-extension-rx/src/main/java/com/instacart/library/truetime/extensionrx/TrueTimeRx.java#L76).
Imho, this means that initialization will silently fail, the client will get onComplete+unsubscribe without any throwable error and it will not be informed that there was an error initializing the library.

A couple quick patches I can think of are using first() or firstOrDefault() instead of take(1) to make it fail loudly, although without much information about the root cause for the failure.

**Comment by kaushikgopal** [comment]
@sebaslogen good eye! So initially i did use `first()` but [switched to `take(1)` intentionally, so as to NOT fail loudly](https://github.com/instacart/truetime-android/commit/a22c1ee05e16c4a1284b6cb44f7215743de2c495#diff-34c03a8d16ed492b062f4be522cef01c) at the time of initialization.

I moved the fail loudly part however when requesting `TrueTimeRx.now()`. We basically [throw an `IllegalStateException`](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/TrueTime.java#L25) if TrueTime was never initialized.

No particularly insightful reason why we made the alternate decision, just found it flowed well when using from our client. ¯\_(ツ)_/¯.

**Comment by sebaslogen** [comment]
That totally makes sense, I guess I was confused because the Readme example shows how to handle error on [initialization](https://github.com/instacart/truetime-android/commit/405127107fa9d5dde62692809686cbeb3693edf5#diff-04c6e90faac2675aa89e2176d2eec7d8R73).

The problem I see with the IllegalStateException is that at compile time the user of the lib is not aware that `TrueTimeRx.now()` can crash. So the library can have lot of IOExceptions thrown during initialization that could be handled at compile time, but instead they are transformed into a RuntimeException that it's more difficult to catch.

**Comment by npace** [comment]
One could argue that throwing an unchecked exception is more of a silent way to fail from the point of view of the library user.

I like the way the vanilla version handles initialization errors because it forces the code dealing with initialization to handle them, providing a tighter abstraction. The Rx version currently kind of forces the callers of `TrueTimeRx.now()` to deal with initialization - I imagine a client using the method must look something like this:
```java
try {
    Date trueTime = TrueTime.now();
} catch (IllegalStateException e) {  // Oh crap it hasn't been initialized
   thingResponsibleForInitialization.initTrueTime(); // probably the Application class or something
}
```

**Comment by kaushikgopal** [comment]
k closing this one out for the time being. feel free to re-open if there's a stronger argument to be made for the opposite side (?).
