### ISSUE TITLE
we don't need to *also* store the boot time

### ISSUE THREAD

**Issue by kaushikgopal** [instacart/truetime-android#18]
boot time = sntp time - device uptime. we shouldn't have 3 flags

https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/DiskCacheClient.java#L12

**Comment by montanalow** [comment]
We do need to cache boot time right? It may change when the device is
rebooted, and we need to check if boot time (cache) + uptime (read) is no
longer consistent with sntp time (cache).

**Comment by montanalow** [comment]
I think we don't need to cache uptime instead, since it should be cheap to read, and we'll want the latest version every second.

**Comment by kaushikgopal** [comment]
> We do need to cache boot time right?

That's right, we would need to know the last boot time but this can easily be derived by `sntpTime` - `deviceUptime`. Currently we're caching all three values but one of those is [anyway derived from the other two](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/DiskCacheClient.java#L39).

> It may change when the device is rebooted

yup, that's right too but rather than checking on every app resume (which would include after app kills for e.g.), we can listen to "boot" events, which is what the [boot broadcast receiver does](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/BootCompletedBroadcastReceiver.java). On every boot we clear the disk cache, so the case you mentioned is accounted for. But we get the advantage of not having to check this on every app resume. just device boots.

**Comment by kaushikgopal** [comment]
> I think we don't need to cache uptime instead, since it should be cheap to read, and we'll want the latest version every second.

we'll need the uptime at the point that sntp was generated. Or alternatively, we could store the boot time (either would work)

**Comment by montanalow** [comment]
Cool. Does the boot broadcast still get delivered even if the app is not running, and then processed after app resume?

**Comment by kaushikgopal** [comment]
so my understanding is that the boot broadcast would be received if the app was ever launched atleast once. i.e. if it was never launched then it wouldn't receive the notification. but if it was launched once, then we should be getting these. i tested this with a basic boot case `adb shell start; adb shell stop` and it looks like it does the trick

**Comment by Bakhrom** [comment]
Probably does not always work this receiver, error log reports show similar:
```
Device time: 2017-02-23T21:12:56.630-05:00
Location time: 2017-02-23T21:12:56.613-05:00 
NTP time: 2017-02-17T13:55:57.835-05:00
```

**Comment by kaushikgopal** [comment]
@Bakhrom : i would encourage you to open a different issue on this. (might be a faulty NTP server ? In that new issue please give me details like which ntp pool server your using and if you've pulled the latest code)

**Comment by kaushikgopal** [comment]
i'm closing this issue out, cause i'm not enthused at the moment to change it. i'm open to PRs: :P
