### ISSUE TITLE
Cannot resolve method build();

### ISSUE THREAD

**Issue by jp1017** [instacart/truetime-android#21]
Your README:

```
TrueTime.build().initialize();
```

It maybe `TrueTime.get().initClient();`

Another is `TrueTime.get().now();`

**Comment by jp1017** [comment]
Oh, release 1.5 now.

But, 1.0 in the README. 😞

**Comment by kaushikgopal** [comment]
@jp1017 Thanks for pointing out. you're right, can be super misleading. updated the README so it'll prompt folks to look at the releases tab. 🙏
