### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by jp1017** [instacart/truetime-android#23]
If connect timeout, throw the exception makes my app dead. :cry: 

```
E/TrueTime: TrueTime initialization failed
 java.lang.Throwable: java.net.SocketTimeoutException at com.instacart.library.truetime.TrueTime.initialize(TrueTime.java:62)
```

**Comment by kaushikgopal** [comment]
@jp1017 : yeah but this is [per design](https://github.com/instacart/truetime-android#exception-handling) though 😕.

the expectation would be to handle the socket timeout exception inside the app (vs the library) and issue a retry. that way, when `TrueTime.now()` is actually called, we're guaranteed a response.

closing this one out, cause i think there's really nothing we can action on here. feel free to reopen if you can suggest alternatives.
