### ISSUE TITLE
Offline Expectations

### ISSUE THREAD

**Issue by ersin-ertan** [instacart/truetime-android#28]
**[Question]**
What kind of guarantees can we expect when offline?
Specifically with the use cases of:

1. user is connected to the internet, user inits truetime, user changes their time, user goes offline, what is the time guarantee for .now()
2. user is connected to the internet, user inits truetime,  user changes their time, user goes offline, app restarts(permission is granted),app is still offline, what is the time guarantee for .now()
3. both 1 and 2 but user goes offline, then changes their time

**Comment by kaushikgopal** [comment]
if TrueTime has successfully initialized even once, you are guaranteed to get the "true" time subsequently always. 

In fact, the use cases you mentioned are exactly why we built the library at Instacart. 

With the new disk caching mechanism we added, we also protect against app restarts. No problems there.

The *only* instance when TrueTime info will be "lost" is a "device" reboot/restart. The TrueTime info kept in sync with the cpu clock ticks and so is reset on a device reboot (see the [broadcast receiver](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/BootCompletedBroadcastReceiver.java)). A device reboot will require TrueTime to be re-initialized.
