### ISSUE TITLE
TrueTime.isInitialized() should not be static

### ISSUE THREAD

**Issue by Shyish** [instacart/truetime-android#29]
It will ALWAYS return false due to:
* SNTP_CLIENT having init flag false by default
* DISK_CACHE_CLIENT having sharedPrefs == null for the same reason

Also having this method static is very confusing since at the beginning you might think that in order to check wether or not you should call initialize you can do the following:

```
if (!TrueTimeRx.isInitialized()) 
    TrueTimeRx trueTimeRx = TrueTimeRx.build()
        .withSharedPreferences(this)
        .initialize(...)
        (...)
```

When in fact you have to do this:
```
TrueTimeRx trueTimeRx = TrueTimeRx.build().withSharedPreferences(this);

    if (!trueTimeRx.isInitialized()) 
        (...)
```

**Comment by kaushikgopal** [comment]
> It will ALWAYS return false

I just tested this in the sample app and this does not appear to be true.

![image](https://cloud.githubusercontent.com/assets/1042037/19603914/cb444528-9767-11e6-9ab7-e1e87556aef6.png)

> Also having this method static is very confusing since at the beginning you might think that in order to check wether or not you should call initialize you can do the following

The intention of `TrueTimeRx.isInitialized()` is to be used when you're actually trying to retrieve the time using `TrueTimeRx.now()`. 

    if (TrueTimeRx.isInitialized()) {
          TrueTimeRx.now();
    }
      
If you haven't initialized and call `now()` you will get an IllegalStateException. This method is a guard/check against that. 

You don't need to perform any check before initializing `TrueTimeRx.initialize()`, just go ahead and do it in your Application create. calling it again will not have any consequence.

closing this out, feel free to reopen if any of the above doesn't make sense. Cheers!

**Comment by Shyish** [comment]
Yes that case makes sense for it being static. What I don't see is that TrueTimeRx do not perform the request if it has the time stored already.

So in the normal TrueTime there's:

```
public void initialize() throws IOException {
        initialize(_ntpHost);
        saveTrueTimeInfoToDisk();
    }
//
protected void initialize(String ntpHost) throws IOException {
        if (isInitialized()) {
            TrueLog.i(TAG, "---- TrueTime already initialized from previous boot/init");
            return;
        }
```

Although in the Rx version:

```
public Observable<long[]> initializeNtp(String ntpPool) {
        return Observable//
              .just(ntpPool)//
              .compose(resolveNtpPoolToIpAddresses())//
              .flatMap(bestResponseAgainstSingleIp(5))  // get best response from querying the ip 5 times
              .take(5)                                  // take 5 of the best results
              .toList()//
              .map(filterMedianResponse())//
```

So I don't see any check in the Rx version to check whether it was initialized already. Actually there's no calls to `isInitialized()` in that class.

Anyway this could be easily checked with an Unit test.

**Comment by kaushikgopal** [comment]
ah! got it.

:) ... so this is something that i've been wrestling with a little. i'm going to open a new issue for this cause i think there's an interesting decision to be made (which doesn't necessarily have to do with it being static).

thanks for pointing that out.
