### ISSUE TITLE
Set TrueLog.LOGGING_ENABLED false by default

### ISSUE THREAD

**Issue by Shyish** [instacart/truetime-android#30]
Having the field true by default causes tests to fail (due to Log class not mocked) unless explicit call to `.withLoggingEnabled(false)` is made.

**Comment by kaushikgopal** [comment]
Changing the default flag to be false makes perfect sense. Thanks!

Out of curiosity, I don't entirely understand how this would cause your tests to fail. Are these UI tests? Integration tests? also what does the logging have to do with the actual testing?

**Comment by Shyish** [comment]
@kaushikgopal Cool, thanks!

The tests are JUnit tests and any call that leads to a Log.something will cause an exception since those are plain java tests.

**Comment by kaushikgopal** [comment]
ah got it! thanks.
