### ISSUE TITLE
should we be checking if Truetime is already initialized ?

### ISSUE THREAD

**Issue by kaushikgopal** [instacart/truetime-android#31]
Question: Should we be checking if TrueTime is initialized already in the `initialize` calls, or should we only be checking at the time of retrieving `now` from TrueTime?

have a look at the last comment from #29 by @Shyish for more context.

Currently in the vanilla version of `TrueTime`: we do the following:

```
public void initialize() throws IOException {
        initialize(_ntpHost);
        saveTrueTimeInfoToDisk();
    }

protected void initialize(String ntpHost) throws IOException {
        if (isInitialized()) {
            TrueLog.i(TAG, "---- TrueTime already initialized from previous boot/init");
            return;
        }
```

With the 2.0 rewrite, i removed the check from `TrueTimeRx`. My thinking was that with the full NTP implementation, trying again could potentially lead to more accurate/ "fresh" results. The vanilla version of TrueTime does not have full NTP implementation, which is why the dilemma of consistency comes to play.

Here are my random questions/thoughts:
- does clock drift affect the accuracy of TrueTime over time. i.e. after executing a successful `TrueTime` init call, can i use the same result for a whole year? is there a concept of "expiry" because of the nature of the drift of a hardware device clock?
  - if yes, then we should definitely not check at the time of init as it avoids the unnecessary network call
  - if no, we should definitely check so as to get a more accurate result

**Comment by kaushikgopal** [comment]
closing this. i'm not convinced of this change yet

**Comment by szymenpl** [comment]
@kaushikgopal 
1. Is there any way to reinitialize vanilia version of TrueTime (make a request to synchronize time)
2. If no, is it something that SNTP doesn't support by design or is it only this library limitation?
