### ISSUE TITLE
Wrong value for root delay and root dispersion

### ISSUE THREAD

**Issue by mhopmann** [instacart/truetime-android#32]
In SntpClient, the root delay and root dispersion are badly calculated.
In the code, they are evaluated as 32bits long. But in the NTP protocol, they are signed fixed point.

> Root delay. 32 bits, signed fixed point.
> The total roundtrip delay to the primary reference source, in seconds with the fraction point between bits 15 and 16. Positive and negative values are valid.
> 
> Root dispersion. 32 bits, signed fixed point.
> The maximum error relative to the primary reference source in seconds with the fraction point between bits 15 and 16. Only positive values greater than zero are valid. 

So currently, for example, instead of having a root delay of 0.0312500s, it is calculated as 2048s and then raised an exception (since it is > 100).

To fix this, the **signed** 'fixed point' integer should be converted to a float value.

```
  /**
   * Convert a 16.16 fixed-point value to floating point
   * @param val The fixed-point value
   * @return The equivalent floating-point value.
   */
  public static float toFloat(int val) {
    return ((float)val)/65536.0f;
  }
```

> http://stackoverflow.com/questions/8638792/how-to-convert-packed-integer-16-16-fixed-point-to-float

**Comment by kaushikgopal** [comment]
@mhopmann 🙏 

apologies for taking this long. i didn't think the calculation was wrong, so kept procrastinating.

finally took the time to read the specs and cross check the logic. you were 💯  right. fantastic catch! it took me a good solid 1 hour to re-read and confirm with the spec to confirm this. 

I've pushed a fix that should now address this. Cheers
