### ISSUE TITLE
Exception upon running example code

### ISSUE THREAD

**Issue by renclav** [instacart/truetime-android#33]
Hi Guys,
Using
compile 'com.github.instacart.truetime-android:library-extension-rx:2.0'

I seem to be getting the following error when running the below from my application's onCreate

```
    TrueTimeRx.build()
            .withSharedPreferences(this)
            .withLoggingEnabled(BuildConfig.DEBUG)
            .withRetryCount(3)
            .initializeRx("0.north-america.pool.ntp.org")
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(date -> {
                //Got the time :)
                if(BuildConfig.DEBUG)
                {
                    DateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ENGLISH);
                    format.setTimeZone(TimeZone.getTimeZone("GMT+02:00"));
                    Toast.makeText(MyApplication.context, "True time retrieved: " + format.format(date), Toast.LENGTH_LONG).show();
                }
            }, throwable -> {
                if(BuildConfig.DEBUG)
                {
                    Toast.makeText(MyApplication.context, "Failed to retrieve true time with error: " + String.valueOf(throwable.getMessage()) , Toast.LENGTH_LONG).show();
                }
                Timber.w(throwable, "Failed to retrieve true NTP time");
            });
```

`rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: java.util.ArrayList.class`

Might this be due to my existing rxjava libs?
compile 'io.reactivex:rxjava:1.2.1'
even if I add
           { exclude group: 'io.reactivex', module: 'rxjava' }
doesn't seem to resolve the issue though

**Comment by kaushikgopal** [comment]
@renclav sorry for not seeing this earlier. 

Can you provide the full exception stack trace that you got? I suspect this is more of an issue with your Rx call chain implementation, than with the TrueTime implementation. The stack trace should help narrow it down

**Comment by kaushikgopal** [comment]
closing this for now. feel free to reopen if you have more info
