### ISSUE TITLE
blog post has 1.5 version listed, but 2.0 code sample

### ISSUE THREAD

**Issue by toddhodes** [instacart/truetime-android#36]
fyi: blog post has the 1.5 version listed in the dependency, but a 2.0 code sample.  a bit tricky to track down as the package changed, too.

**Comment by kaushikgopal** [comment]
good call! thanks for pointing it out. i've changed our blog post to `<release-version>` so folks would most likely just look at either the sample (which should keep pace with the newest version) or the latest release (which would be ideal :) )
