### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by eranpolo** [instacart/truetime-android#43]
When trying to use the TrueTime RX version (via compile 'com.github.instacart.truetime-android:library-extension-rx:2.2'), I get a failure saying "Manifest merger failed". The problem is that the TrueTime library contains an android:label field in its manifest. Perhaps the library can do without specifying it?
Note that the same offending value was removed from the non-RX version (commit fb8c9f0c1716e74cef71303c44a4cff886e251aa).

(btw, this can be fixed by overriding the android:label via tools:replace, but that's a less elegant solution)

**Comment by kaushikgopal** [comment]
👍 PR pretty please :) ?

**Comment by eranpolo** [comment]
Done :)
https://github.com/instacart/truetime-android/pull/44
