### ISSUE TITLE
initializeRx with multiple urls?

### ISSUE THREAD

**Issue by scottybe** [instacart/truetime-android#46]
I'm using this awesome library for both iOS and Android.

The iOS version has a startWithHostURLs method which accepts an array of NTP urls. (I randomize the order of my NTP server pool given to me by ntp.org since I expect a lot of devices to start near the same time, assuming that makes a difference.)

The Android example shows an initializeRx method which takes a single "NTP pool server host" url with the note "the NTP pool address you provide is resolved into multiple IP addresses." I'm a little confused by that. For example, if I want to use 0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org, and 3.pool.ntp.org, should I pass one of them (randomly selected) or should I pass "pool.ntp.org" or is there a better/correct option?

New comment:
I used http://ping.eu/nslookup to look up the urls in my pool, and each one returns the same 4 IP addresses but in different orders. That's true for 0.pool.ntp.org - 3.pool.ntp.org as well. Therefore, I see that I can just pass one of the pool urls to initializeRx. Is it possible to "spread the load" equally among all the IP addresses by randomly selecting which url I pass, or does it not matter which one I pass?

Thanks!

**Comment by kaushikgopal** [comment]
@scottybe firstly thank you so much for the kind words.

astute observations. i've actually thought about this in the past but couldn't come up with a convincing enough way out. so i'm going to brain dump here and hopefully, we can come up with something jointly (possibly) if it's worth it.

## Super basic dns resolution

currently, when you provide an ntp pool address, we use the most "basic" dns lookup and get 5 ip addresses from that resolution effort. So i spun up the app now and provided two "pool" addresses, here's what i get:

```
time.google.com
216.239.35.4
216.239.35.4
216.239.35.4
216.239.35.4
216.239.35.4

time.apple.com
17.253.24.253
17.253.24.125
17.253.26.125
17.253.4.253
17.253.4.253
```

So as you can see, the dns lookup doesn't intelligently filter unique ips at the moment. it simply asks for 5 addresses and goes about it's business. As you can see right now, it's just up to what the ntp "pool" server gives us back. 

We can potentially modify it to filter out unique, but I haven't come across anything in the spec where they say that the request must be made to an individual ip address ¯\_(ツ)_/¯.

## Shouldn't sync across multiple ntp pool servers

What i *have* run across from the spec, is that it's a *bad* idea to sync across different pool addresses, so if i send in both `time.apple.com` and `time.google.com` and get 2 from the first pool and 3 from the second pool, that is a no no. different ntp pool servers use different synchronization/correction mechanisms.

Given the above, i was not heavily enthused to add "true" multiple url host urls.

In practice, from our analytics, it appears like this strategy is doing pretty well. 

Thoughts? was this question driven from curiosity or are you running into a problem specifically that would help inform our next set of actions here?

Cheers

**Comment by kaushikgopal** [comment]
going to close this out for now, feel free to reopen if you have thoughts/feedback :v:
