### ISSUE TITLE
initializeRx goes well, but difference with local time is highly variable

### ISSUE THREAD

**Issue by carlobono** [instacart/truetime-android#48]
Hi everyone and thank you for your code

In my app I get a correct initialization, and then a pretty stable delta with local time when polling every second.
If I restart the application on my Android, the delta is very similar (up to milliseconds).

Fact is, If I restart the application after a day or hours, the delta is very different (can be like seconds different from before!), but still pretty stable if I relaunch the application consecutively.

The application just prints TrueTimeRx.now().getTime()-System.currentTimeMillis();
so I don't think there is some exotic problem there.

Initialization also is done with a wild copypasta:

        TrueTimeRx.build()
                .initializeRx("time.google.com")
                .subscribeOn(Schedulers.io())
                .subscribe(date -> {
                    Log.e("TAG", "TrueTime was initialized and we have a time: " + date);
                }, throwable -> {
                    throwable.printStackTrace();
                });

Tested on two Android phones (Samsung S6 and Motorola Moto G4).

Any suggestion on what I should investigate?
Thanks in advance

CB

**Comment by kaushikgopal** [comment]
@carlobono - @msanders and I actually have a follow up blog post having used truetime in the wild for sometime now (that we should push out at some point; hopefully soon).

this future blog post, would actually add in some recommendations that we found critical.

so if i understand your problem, the issue you're seeing is "clock drift". the cpus on our devices inherently are flawed with the drifts. so a clock tick varies (of the order of milliseconds) between different devices vs what is truly a milli/nano second clock tick.

so what do you do?

you have to keep re-initializing TrueTime in the background. This would obviously vary depending on the device you use, but from my analysis on android devices, an interval of 5 minutes has worked pretty well. this is very similar to what we have in production 👇 

```
   Observable.interval(5, TimeUnit.MINUTES)
        .filter(l -> !mOfflineModeApi.isOffline())
        .filter(l -> !isInBackground())
        .doOnNext(l -> runTrueTimeInit())
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe();
```
So this tries to keep TrueTime as close as possible to  "real" time. Sure, if we don't get internet connectivity for sometime, the local data is good enough to hold out for sometime, but the idea is given clock drift you want to keep re-syncing as frequently as possible.

(btw, this is how all mobile devices keep time so we're not doing anything crazy here :) )

**Comment by carlobono** [comment]
hi @kaushikgopal 
first of all thank you for your clear response.

I was discarding this hypothesis because the delta between clocks basically had some seconds of error even in half a day.

But if the error can be around this scale (eg 1,2,3 seconds on 24 hours, depending on device) then I suppose that drifting + os network time sync explains it.
Is this possible? Or drifting error is usually smaller (eg milliseconds, tens of milliseconds...)

Please keep me posted for when you'll blog about this! I'm very interested.
Meanwhile, do you have any reference (possibly with benchmarks) on this drifting effect? I tried to have some googling but I found nothing specific enough.

Thank you for your help and time
Best
CB

**Comment by kaushikgopal** [comment]
@carlobono most welcome.

We have definitely seen order of second differences on some low cost devices. Some low cost burner devices particularly are notorious. We had a graph that showed us internally how "bad" the drift was, compared to what we "thought" was the real time (from server mappings).

We'll definitely try to see if there's a way to present that data outside. Since it's tied up with a lot of our internal functionality and what we use TrueTime for, it's a little tricky presenting that data in a meaningful way, but will try to work on it :v:.

i'm closing this issue out, but i'll definitely ping you here once we have that blog post out. thanks again !

**Comment by carlobono** [comment]
Thanks to you!
Much appreciated.

Have a nice well... everything
CB
