### ISSUE TITLE
Server response delay too large for comfort

### ISSUE THREAD

**Issue by MahdiHatami** [instacart/truetime-android#50]
is there any way to increase the minimum delay, current is 100.

**Comment by kaushikgopal** [comment]
hey @MahdiHatami 

I imagine you mean [this delay](https://github.com/instacart/truetime-android/blob/ed1acd826724c7e1da88d4c98660ba8f976da390/library/src/main/java/com/instacart/library/truetime/SntpClient.java#L140-L140)?

Unfortunately no. This requirement comes as part of the NTP spec, so wouldn't be wise for us to change that.

**Comment by MahdiHatami** [comment]
hey @kaushikgopal 
with "time.google.com" as NTP server cannot i'm not able to get the date by changing it to apple server it works.
