### ISSUE TITLE
Using TrueTime.withSharedPreferences returns wrong time

### ISSUE THREAD

**Issue by consp1racy** [instacart/truetime-android#52]
TT version: 2.2

Just got back a five days old time. 

Happened in Genymotion Samsung Galaxy S4 API 17. It also happens on real devices, cannot pinpoint which, since we dismissed the problem at the time.

It is independent of used NTP pool.

Contents of shared prefs:
```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<long name="com.instacart.library.truetime.cached_sntp_time" value="1491132884332" />
<long name="com.instacart.library.truetime.cached_boot_time" value="1491132738971" />
<long name="com.instacart.library.truetime.cached_device_uptime" value="145361" />
</map>
```

This may be related to sleep. I put my computer to hibernate, the emulator gets confused when woken up. HTC devices have some sort of soft reboot. Just tossing ideas...

Removing the `.withSharedPreferences` line fetched time from network and provides correct results.

**Comment by kaushikgopal** [comment]
hey @consp1racy 🤔  this is interesting (/troubling).

* i see your device_uptime value and it's super "low" so i presume it was after a recent reboot, which hints towards some possibilities.
* technically after a reboot, the cached time is very very INCORRECT. cause the device uptime is how we manage to calculate the offset for TrueTime.
* to account for this problem specifically, we have [the broadcast receiver that listens to reboots](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/BootCompletedBroadcastReceiver.java)

so my first question would be, could you confirm with the Genymotion simulator if the broadcast receiver actually fires?

that'll help indicate which direction we should be looking to solve this problem

**Comment by consp1racy** [comment]
If I understand correctly any use of TrueTime between application start (Application.onCreate, ContentProvider.onCreate) and the boot receiver will yield incorrect results.

Wouldn't the solution be having an empty ContentProvider (CPs get initialized before Application.onCreate and any BroadcastReceivers) check if cached boot time equals actual boot time and if not clear the cache?

---

According to [this](http://stackoverflow.com/questions/20441308/boot-completed-not-working-android) HTC need special treatment for their Quickboot option:

     <intent-filter>
          <action android:name="android.intent.action.BOOT_COMPLETED" />
          <action android:name="android.intent.action.QUICKBOOT_POWERON" />
     </intent-filter>

[Another source](https://twitter.com/jcase/status/440207669408718849) suggests:

     <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" />

**Comment by consp1racy** [comment]
Because `BOOT_COMPLETED` action comes in too late (and the event is not needed by application logic) I've devised the following solution:

### TrueTimeInitProvider.java

As mentioned earlier, a Content Provider is initialized before `Application.onCreate` which itself precedes `BroadcastReceiver.onReceive`. We compare cached Boot Time (i.e. time of boot) to boot time derived at the time of Content Proider creation. The cached and computed times are typically within 1 second range. If these times differ more than delta 1s we clear the cached boot time - it's obvious the device rebooted.

This code uses ThreeTenABP which is probably unnecessary. `java.util.Date` is safe to use with system/default time zone.

Since boot takes longer than 1s, it's safe to use a slightly bigger value.

```
public class TrueTimeInitProvider extends ContentProvider {
    static final String KEY_BOOT_TIME = "boot-time";

    @NonNull
    static SharedPreferences getSharedPreferences(@NonNull final Context context) {
        return context.getSharedPreferences("tt2", Context.MODE_PRIVATE);
    }

    @Nullable
    static ZonedDateTime getCachedBootTime(@NonNull final SharedPreferences prefs) {
        final String cachedBootTimeStr = prefs.getString(KEY_BOOT_TIME, null);
        final ZonedDateTime cachedBootTime;
        if (cachedBootTimeStr != null) {
            cachedBootTime = ZonedDateTime.parse(cachedBootTimeStr);
        } else {
            cachedBootTime = null;
        }
        return cachedBootTime;
    }

    static void putCachedBootTime(@NonNull final SharedPreferences prefs, @NonNull final ZonedDateTime actualBootTime) {
        prefs.edit().putString(KEY_BOOT_TIME, actualBootTime.toString()).apply();
    }

    @Override
    public boolean onCreate() {
        final Context context = getContext();
        assert context != null;
        final SharedPreferences prefs = getSharedPreferences(context);

        final ZonedDateTime cachedBootTime = getCachedBootTime(prefs);
        final long realtimeNanos = SystemClock.elapsedRealtimeNanos();
        final ZonedDateTime actualBootTime = ZonedDateTime.now().minusNanos(realtimeNanos);

        if (cachedBootTime == null || Math.abs(cachedBootTime.toEpochSecond() - actualBootTime.toEpochSecond()) > 1L) {
            putCachedBootTime(prefs, actualBootTime);

            TrueTime.clearCachedInfo(context);
        }

        return false;
    }

    // Rest of class is omitted for clarity.
}
```

### TrueTimeChangeReceiver.java

Here we account for the fact that wall clock may change. In that case we need to update the cached boot time. Boot time actually didn't change. Once the value is updated, ContentProvider won't clear cache when the app process starts again. Unless the device reboots of course.

```
public class TrueTimeChangeReceiver extends BroadcastReceiver {
    private static final String TAG = TrueTimeChangeReceiver.class.getSimpleName();

    @Override
    public void onReceive(final Context context, final Intent intent) {
        final String action = intent.getAction();
        if (Intent.ACTION_TIME_CHANGED.equals(action) || Intent.ACTION_TIMEZONE_CHANGED.equals(action)) {
            Log.w(TAG, "Time changed.");

            // Save new boot time but DON'T clear cache as we didn't actually reboot or anything.
            final long realtimeNanos = SystemClock.elapsedRealtimeNanos();
            final ZonedDateTime newBootTime = ZonedDateTime.now().minusNanos(realtimeNanos);
            final SharedPreferences prefs = TrueTimeInitProvider.getSharedPreferences(context);
            TrueTimeInitProvider.putCachedBootTime(prefs, newBootTime);
        } else {
            Log.e(TAG, "Received unsupported intent " + intent);
        }
    }
}
```

### AndroidManifest.xml

And finally register both components in the manifest. The time change receiver is safe to use as [both intent actions are exempt from the implicit broadcast ban coming in Android O](https://developer.android.com/preview/features/background-broadcasts.html).

```
<manifest>
    <application>
        <provider
            android:name="com.instacart.library.truetime.TrueTimeInitProvider"
            android:authorities="${applicationId}.truetime"
            android:exported="false"/>

        <receiver android:name="com.instacart.library.truetime.TrueTimeChangeReceiver">
            <intent-filter>
                <action android:name="android.intent.action.TIME_SET"/>
                <action android:name="android.intent.action.TIMEZONE_CHANGED"/>
            </intent-filter>
        </receiver>
    </application>
</manifest>
```

I'm notorious for bad explanations so let me know if something isn't clear ^^

**Comment by gloryluu** [comment]
I've got the wrong time issue also on some Asus Zenphone Max devices. The time is correct at some very first time. After 3-4 days later, the result from TrueTime.now() returns wrong. 
Do you know what cause the reason?
Do you think this device need to declare some any special permission?

**Comment by kaushikgopal** [comment]
we have a PR #62 that another contributor is helping with. Once they have that PR merged in, i intend to take a more exhaustive look at this again. stay tuned.

**Comment by kaushikgopal** [comment]
so the caching changes are in version `3.4`, that being said there's an edge case that still hasn't been accounted for. This is documented here -> https://github.com/instacart/truetime-android/issues/85

closing this issue out. let me know if we're missing anything
