### ISSUE TITLE
Question: does Android only use SNTP and no NTP?

### ISSUE THREAD

**Issue by GillesC** [instacart/truetime-android#53]
Hello

First of all, thank you for your excelent library.

I'm I correct to assume to Android uses SNTP to correct its internal system clock? Thereby, providing a less accurate timestamp opposed to using NTP. Because I've noticed that using SNTP the computed offset between the internal clock and the SNTP-time is highly variable.

Kind regards,
Gilles Callebaut

**Comment by kaushikgopal** [comment]
@GillesC - you're most welcome 🙏 . thanks for having a look at this library.

I would love to answer that question :D.

Initially we [only did SNTP](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/SntpClient.java). If you use the vanilla version of the library (i.e. without Rx), then the library only does SNTP.

If you use the Rx version, then it's full-on NTP.

[This note in the Readme points to the other advantages of using the Rx version](https://github.com/instacart/truetime-android#what-is-nifty-about-the-rx-version).

Hope that answers your question!

**Comment by GillesC** [comment]
Thank you for your comment. But what I was trying to ask was, does the Android OS itself use SNTP? And thus, we (developers) need to use your library to keep a global correct time?

**Comment by kaushikgopal** [comment]
ah misunderstood. my bad.

Android internally __definitely__ uses NTP (not SNTP). The only reason to use this library is because that NTP implementation is not exposed by AOSP. So if you wanted to use that logic in your app, you won't be able to.

Also, a use can override that time, by changing the date/time. If you go to settings and don't pick "Automatically set Date/Time", then if you new Date in your app, you'll get a different time, not the true NTP time.

Hope that clarifies it a bit?

**Comment by GillesC** [comment]
So you are saying that Android itself uses NTP?
But In the source code of the [NetworkTimeUpdateService](https://android.googlesource.com/platform/frameworks/base/+/jb-dev/services/java/com/android/server/NetworkTimeUpdateService.java) a [NtpTrustedTime ](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/util/NtpTrustedTime.java)object is used to request the current time. This object uses a SNTPClient to retrieve a time value from an NTP server, as can be seen [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/util/NtpTrustedTime.java#103).

Or am I wrong?
