### ISSUE TITLE
Neither Rx version or Normal version is working

### ISSUE THREAD

**Issue by parthmg** [instacart/truetime-android#54]
Hi,

Neither Rx version or Normal version is working. Even the Sample is not working

Getting the same error everywhere. Even in Rx version where retry happens 100 times. Also the exception crashes the App.

```
com.instacart.library.truetime.InvalidNtpServerResponseException: Server response delay too large for comfort 378
                                                                                   at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:171)
                                                                                   at com.instacart.library.truetime.TrueTime.requestTime(TrueTime.java:89)
                                                                                   at com.instacart.library.truetime.TrueTime.initialize(TrueTime.java:85)
                                                                                   at com.instacart.library.truetime.TrueTime.initialize(TrueTime.java:49)
                                                                                   at com.instacart.library.sample.SampleActivity$InitTrueTimeAsyncTask.doInBackground(SampleActivity.java:73)
                                                                                   at com.instacart.library.sample.SampleActivity$InitTrueTimeAsyncTask.doInBackground(SampleActivity.java:65)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
```

**Comment by GauravP123** [comment]
@kaushikgopal yes same error i am getting

**Comment by simon-the-canadian** [comment]
I have some devices that TrueTime never gets initialized on because of this exact issue. 
It seems to me like the acceptance threshold should be customizable by the client. Right now the threshold is hardcoded to 100 milliseconds. For my use of the library I don't need it to be that strict.

**Comment by kaushikgopal** [comment]
@parthmg : can you give more info, like what device you're testing on, are you behind a VPN/firewall, all this is useful info in diagnosing what's problematic. 

> Neither Rx version or Normal version is working. Even the Sample is not working

I assure you, the library works under most normal settings :). we use this live in production at Instacart, and it's critical to our path flow. If it wasn't working we'd run into *major* problems.

all that being said, most of our users are in the US (so i understand it's a different set of conditions) so if you can send info on what settings you're running into problems, that would be super helpful in increasing the stability of the library.

> Also the exception crashes the App.

Does the Sample app crash for you? are you using the Rx version? are you handling the onError callback? if you're cascading it up, without catching that exception, it definitely will crash your app [as it's an IO exception](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/InvalidNtpServerResponseException.java)

**Comment by kaushikgopal** [comment]
@GauravP123 if you could also provide similar info as pointed in my last comment, that would be helpful

**Comment by kaushikgopal** [comment]
@simon-the-canadian : thanks for the PR.

here's the trouble though: that server response delay is not a custom setting we have chosen, those are part of the NTP spec. 

we _could_ add this as a custom setting, and sure it'll "work" but that time according to the NTP spec would not be accurate. then you'll start seeing inconsistent-or worse- incorrect times. that's definitely a far worse problem.

Note: others have run into the problem, that's why [we added this section in the wiki which is the exact same issue you folks are running into](https://github.com/instacart/truetime-android#troubleshootingexception-handling).

I'm open to seeing if the conditions you're seeing this are a little different though.

**Comment by simon-the-canadian** [comment]
@kaushikgopal Thanks for the response. I can see how following the NTP spec would prevent allowing a larger delay time. I guess in that case the only option would be to just increase the retry rate and hope it eventually succeeds.

**Comment by parthmg** [comment]
@kaushikgopal Thanks for the response

>  can you give more info, like what device you're testing on, are you behind a VPN/firewall, all this is useful info in diagnosing what's problematic.

I am using Moto G and tried it on Wifi as well as Cellular, Wifi is behind a firewall but Cellular ain't.
I am trying it in India though. I tried time.apple.com as well as the default one.

> Does the Sample app crash for you? are you using the Rx version? are you handling the onError callback? if you're cascading it up, without catching that exception, it definitely will crash your app as it's an IO exception

Yes the Sample App is not working for both Normal and Rx.

**Comment by lisandrop** [comment]
We have been trying connected through WiFi with 10000 retries while logging the result speeds, the fastest we could acquire was 133 milliseconds against time.google.com and time.apple.com. 

We are in south america so we tested all of these servers in Chile:
http://www.pool.ntp.org/zone/cl

No luck either. 

I dont know how you guys are so confident about how well the API works. Ive been testing this for hours without being able to run the most basic test.

**Comment by kaushikgopal** [comment]
@parthmg hmm Sample app working indicates this is more of a localized problem, meaning in the specific conditions you're in, there's some weirdness with the ntp servers.

let's try to figure out why the sample app is not working for you and base findings on that, as i'm not entirely sure how you're calling it within your app. it'll be easier to debug

* user `time.google.com` as your ntp pool address
* user the Rx version (you are definitely not going to have better luck with the Vanilla version)
* avoid any firewalled connections just to reduce ambiguity
* how many retries have you set when initializing TrueTime?

>  the Sample App is not working 

what does this mean? is it "crashing" or are you "not seeing time". you'll have to be specific in order for us to debug this.

**Comment by kaushikgopal** [comment]
@lisandrop 

> I dont know how you guys are so confident about how well the API works. Ive been testing this for hours without being able to run the most basic test.

😞  not sure what to say. we and many many others are using this library without problems. granted more of the success stories i know have been from North America, so not sure if that's playing a part

can you also provide the info like i've asked from Parth ?

if you can try the same combination in my last comment and report on your findings, that would also be helpful.
