### ISSUE TITLE
"expected SNTP time from last boot to be cached. couldn't find it." with disabled caching

### ISSUE THREAD

**Issue by consp1racy** [instacart/truetime-android#56]
TrueTime 2.2, disabled caching

The code is called in an `Application` class before true time is ever kicked off.

    fun millis() = if (TrueTime.isInitialized()) TrueTime.now().time else System.currentTimeMillis()
    fun instant() = Instant.ofEpochMilli(millis())!!
    fun now() = OffsetDateTime.ofInstant(instant(), ZoneId.systemDefault())!!

    Caused by java.lang.RuntimeException: expected SNTP time from last boot to be cached. couldn't find it.
        at com.instacart.library.truetime.TrueTime._getCachedSntpTime(SourceFile:122)
        at com.instacart.library.truetime.TrueTime.now(SourceFile:28)
        at cz.quickjobs.android.util.Utils.millis(SourceFile:152)
        ...

**Comment by kaushikgopal** [comment]
@consp1racy - i know what's happening, but don't know how it's happening.

* might seem misleading but cache here doesn't refer to the disk cache, but rather the memory cached time
* so basically we are getting a fix for the actual time, storing it in memory, but when we're going to retrieve it, it's not longer available

are you able to reproduce this locally or is this from a crash report? if you can reproduce this locally, that'll be super helpful.

**Comment by consp1racy** [comment]
I'm kinda swamped right now, but I suspect a synchronization problem as I access TrueTime from all kinds of threads simultaneously. One of those threads is responsible for setting up true time, N more try to access it.

**Comment by kaushikgopal** [comment]
pushed a patch, have a shot at pulling the commit `fe72999` directly from jitpack. monitoring this on our side as well.

i can push a patched release, if this does the trick

**Comment by kaushikgopal** [comment]
`886acc1` seems to have done the trick. @consp1racy pull v `3.2`  and feel free to reopen if it hasn't solved the issue.

**Comment by lemberh** [comment]
Have similar issue

> Caused by java.lang.RuntimeException: expected SNTP time from last boot to be cached. couldn't find it.
       at com.instacart.library.truetime.TrueTime._getCachedSntpTime(TrueTime.java:170)
       at com.instacart.library.truetime.TrueTime.now(TrueTime.java:32)
       at com.instacart.library.truetime.TrueTimeRx.initializeRx(TrueTimeRx.java:89)

Crash is happening here

       TrueTimeRx.build()
                .withSharedPreferencesCache(ctx)
                .withRetryCount(20)
                .withConnectionTimeout(30_000)
                .withLoggingEnabled(BuildConfig.DEBUG)
                .initializeRx("time.google.com")   //this line
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())

**Comment by dragon-deali** [comment]
It happend to me in v3.5.

```kotlin
Fatal Exception: java.lang.RuntimeException
java.lang.RuntimeException: expected SNTP time from last boot to be cached. couldn't find it.

android.app.ActivityThread.performResumeActivity (ActivityThread.java:5378)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5444)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:54)
android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2574)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8762)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)

-----

Caused by java.lang.RuntimeException
expected SNTP time from last boot to be cached. couldn't find it.
com.instacart.library.truetime.TrueTime._getCachedSntpTime (TrueTime.java:170)
com.instacart.library.truetime.TrueTime.now (TrueTime.java:32)
```
