### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by innovation-lab234** [instacart/truetime-android#58]
Failed to resolve
compile 'com.github.instacart.truetime-android:library-extension-rx:2.1'

**Comment by kaushikgopal** [comment]
Please have a look at the [releases page](https://github.com/instacart/truetime-android/releases) for the latest version. 

I just pushed `3.3` now and `compile 'com.github.instacart.truetime-android:library-extension-rx:3.3'` seems to work for me.
