### ISSUE TITLE
Is there a way to initialize with a list of ntphosts?

### ISSUE THREAD

**Issue by midaslefkowitz** [instacart/truetime-android#65]
It [used to be possible](https://github.com/instacart/truetime-android/blob/1ca4b1fa5ad4f90abea7465829dbc4ed2fcc621e/library-extension-rx/src/main/java/com/instacart/library/truetime/extensionrx/TrueTimeRx.java#L50) but for some reason it was removed. Any reason why?

**Comment by tutrieuchau** [comment]
You can try it https://www.youtube.com/watch?v=J2neLzU3jbQ

**Comment by yitz-grocerkey** [comment]
That was version 1.5 of TrueTime, the library has since changed for some reason...

**Comment by midaslefkowitz** [comment]
That was version 1.5 of TrueTime, that initialization method has since been removed.

**Comment by tutrieuchau** [comment]
@midaslefkowitz When i look into Source code I see this method 
 public Flowable<long[]> initializeNtp(List<InetAddress> resolvedNtpAddresses) {
        return Flowable.fromIterable(resolvedNtpAddresses)
               .compose(performNtpAlgorithm());
    }
I think it can solve your problem

**Comment by midaslefkowitz** [comment]
The docs for that method clearly indicate that this is not a list of host url Strings (as does the type of param it accepts). 

 /**
* Initialize TrueTime
* Use this if you want to resolve the NTP Pool address to individual IPs yourself
*
* See https://github.com/instacart/truetime-android/issues/42
* to understand why you may want to do something like this.
*
* @param resolvedNtpAddresses list of resolved IP addresses for an NTP
* @return Observable of detailed long[] containing most important parts of the actual NTP response
* See RESPONSE_INDEX_ prefixes in {@link SntpClient} for details
*/



On September 12, 2017, at 5:28 AM, tutrieuchau <notifications@github.com> wrote:

@midaslefkowitz When i look into Source code I see this method
public Flowable<long[]> initializeNtp(List resolvedNtpAddresses) {
return Flowable.fromIterable(resolvedNtpAddresses)
.compose(performNtpAlgorithm());
}
I think it can solve your problem

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/instacart/truetime-android","title":"instacart/truetime-android","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/instacart/truetime-android">https://github.com/instacart/truetime-android</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tutrieuchau in #65: @midaslefkowitz When i look into Source code I see this method \r\n public Flowable\u003clong[]\u003e initializeNtp(List\u003cInetAddress\u003e resolvedNtpAddresses) {\r\n return Flowable.fromIterable(resolvedNtpAddresses)\r\n .compose(performNtpAlgorithm());\r\n }\r\nI think it can solve your problem"}],"action":{"name":"View Issue","url":"<a href="https://github.com/instacart/truetime-android/issues/65#issuecomment-328713946">https://github.com/instacart/truetime-android/issues/65#issuecomment-328713946</a>"}}}

**Comment by kaushikgopal** [comment]
@tutrieuchau - you can use the api provided here https://github.com/instacart/truetime-android/blob/6d9d9288fc49eeda5cd8c3a566cf11d4220a5e69/library-extension-rx/src/main/java/com/instacart/library/truetime/TrueTimeRx.java#L116 if you _really_ want to do that. But i would advise against that. 

You want to provide ntp servers that are in "sync". It's out of scope to explain in this issue, but basically the ideal way to use this is provide a single ntp "pool" address to TrueTime, which it will then resolve to individual ip addresses from that same pool.

If you provide multiple ntp pool addresses, there is a high chance that they would not be in sync amongst themselves and you would get an inaccurate time. If you however plan to do the resolution yourself and provide independent ip addresses, then use the api i mentioned above. 

hope this resolves your query.
