### ISSUE TITLE
How to use TrueTime with my ntp server like 192.168.11.20:123 (Domain server = ntp server)

### ISSUE THREAD

**Issue by tutrieuchau** [instacart/truetime-android#66]

**Comment by tutrieuchau** [comment]
I fould some app like SNTP server can sync time with my domain like (SNTP, SyncClock) but i don't know how they do it, i think TrueTime library can do it, but when i try it alway return error "Invalid response from NTP server. root_dispersion violation. 10731.323242 [actual] > 100.000000 [expected]"

**Comment by kaushikgopal** [comment]
@tutrieuchau - basically the value being returned from that server you're trying (presumably `192.168.11.20` is returning an incorrect value). atleast that's what the error you posted is saying.

root dispersion > 100 means a highly inaccurate value. See [the readme section](https://github.com/instacart/truetime-android#troubleshootingexception-handling) explaining this

**Comment by fstian** [comment]
TrueTime.build().withRootDispersionMax(100000);
