### ISSUE TITLE
Failed to resolve in 3.3

### ISSUE THREAD

**Issue by StevenTB** [instacart/truetime-android#67]
Hi,

I build in SDK target/compile at 26, min is set as 16, and I still have an issue even I added these two repositories : 

> Error:Failed to resolve: com.github.instacart.truetime-android:library:3.3
> Error:Failed to resolve: com.github.instacart.truetime-android:library-extension-rx:3.3

I have to specify that I need to integrate an external SDK (`net.crowdconnected.androidcolocator:colocator:2.0.0` from` http://maven.crowdconnected.net` repository)

Do I have to implement RxJava in my project or something else before ?

Kind regards, and thanks in advance for your help !

Steven

**Comment by skliba** [comment]
@StevenTB how did you fix this? I'm experiencing the same issue?
