### ISSUE TITLE
ANR Input dispatching timed out

### ISSUE THREAD

**Issue by ding33211** [instacart/truetime-android#72]
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 14. Wait queue head age: 19030.9ms.)

```
1 com.instacart.library.truetime.c.a(SntpClient.java:225)
2 com.instacart.library.truetime.e.b(TrueTime.java:41)
```

we just use TrueTime like this
```
public class TimeUtils {
        public static long getTrueTimeStamp() {
                if (TrueTime.isInitialized()) {
                    return TrueTime.now().getTime() / 1000;
                } else {
                    return getDeviceTimeStamp();
                }
        }    
} 
```

**Comment by kaushikgopal** [comment]
@ding33211 couple of things:

1. you have to initialize `TrueTime.init` in a background thread as it would be a network operation. After it has been successfully initialized you can get a hole of `Truetime.now`. Is this the case for you? i.e. has TrueTime been initialized in your case or not?
2. You might also want to look at #80 where we've made some improvements in the UI locking
