### ISSUE TITLE
Bad locking causing deadlocks.

### ISSUE THREAD

**Issue by fifteenhex** [instacart/truetime-android#74]
If the library is initialized asynchronously like with initializeRx() a deadlock happens if you try to get the time before initialization has completed because the initialization process and the check for initialization want to lock the SntpClient instance.

Maybe change the initialized flag to an AtomicBoolean so it has it's own locking?

**Comment by danielpsantiago** [comment]
getting the same error here

**Comment by cmagnuson** [comment]
Seeing the same here - with a poor connection, SntpClient.requestTime locks SntpClient which causes calls to wasInitialized() from UI thread to block for a very long time

**Comment by kaushikgopal** [comment]
apologies for replying so late. I actually have had a branch [kg/fix/sync_to_atomic](https://github.com/instacart/truetime-android/tree/kg/fix/sync_to_atomic) for sometime that should address this.

PR #80 should address this. 

Alternatively, you can try importing that branch directly and seeing if it addresses your issue.

**Comment by kaushikgopal** [comment]
`master` should have the required fixes now. If you're eager to take this before it hits `3.4` try:

`implementation com.github.instacart.truetime-android:library-extension-rx:09087b6a6e`

**Comment by kaushikgopal** [comment]
closing this out as I'm hoping the newer version of this lib has resolved this issue

**Comment by azjkjensen** [comment]
Updating to 3.4 fixed the issue for me.
