### ISSUE TITLE
SometimesGetting wrong TrueTime 

### ISSUE THREAD

**Issue by neelpuniwala** [instacart/truetime-android#76]
I am using withSharedPreferences but I want reInitialized TrueTime whenever Network is Available because sometimes it gives Wrong Time. In my case, TrueTime is Initilized when MainActivity open. Thanks!!

**Comment by kaushikgopal** [comment]
@neelpuniwala keep an eye out for #62. I've seen other reports too fo the `withSharedPreferences` not working as advertised. Once that PR is merged in, I can give it another shot and clean it up

**Comment by kaushikgopal** [comment]
`master` should have the required fixes now. If you're eager to take this before it hits `3.4` try:

`implementation com.github.instacart.truetime-android:library-extension-rx:09087b6a6e`

**Comment by kaushikgopal** [comment]
closing this out. feel free to raise it again if there's still inconsistencies
