### ISSUE TITLE
Server response delay too large 

### ISSUE THREAD

**Issue by sshakilms** [instacart/truetime-android#88]
_com.instacart.library.truetime.InvalidNtpServerResponseException: Server response delay too large for comfort 461
at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:171)_

My Code:
```

    public static final String trueTime_Server_Google="time.google.com";
    public void initTrueTime() {
        //check whether truetime already init
        if (TrueTime.build().withSharedPreferences(this.getApplicationContext()).isInitialized()) {
            Log.d(TAG, "initTime(): TrueTime is already initialized per this boot - using cache!");
            return;
        }
Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    TrueTime.build()
                            .withNtpHost(trueTime_Server_Google)
                            .withConnectionTimeout(3_1428)
                            .initialize();
                    Log.d(TAG, "TrueTimeSynced: " + TrueTime.now() + "/" + TrueTime.isInitialized());
                } catch (Exception e) {
                    e.printStackTrace();
                    Log.d(TAG, "TrueTimeSynced Failed");
                }
            }
        });

        thread.start();
}
```

I am tried this code with MotoDevices and MI devices but
it not worked after that i download from git hub truetime project sample but same issue coming with theme. 
Setting device Time on Synce and internet also working fine .
**Using TrueTime Library Version = 3.3 
Device location India Maharashtra GMT+05:30

i tried with different NTP Servers  :
    public static final String trueTime_Server_Google="time.google.com";
    public static final String trueTime_Server_Apple="time.apple.com";
    public static final String trueTime_Server_NTP="pool.ntp.org";**

**Comment by dennismunene** [comment]
Also having the same problem

**Comment by sshakilms** [comment]
my code working fine in past some months but from 2 days error occurred. how we can check NTP server working or may be latest Truetime version error.

**Comment by anugotta** [comment]
Getting the same issue with "time.google.com"; "0.pool.ntp.org" and "0.uk.pool.ntp.org" works on multiple retries.

**Comment by kaushikgopal** [comment]
sorry folks, this is expected. here's what I'd suggest:

* use the newest version of TrueTime `implementation com.github.instacart.truetime-android:library-extension-rx:09087b6a6e` and see if you're still running into this issue
* in the newest version of the library we've upped the server response time threshold, see [this issue for more clarity](https://github.com/instacart/truetime-android/pull/71). 

There's a lot of documentation around the README and some of the closed issues too around this. Please have a look a those and if there's something specific that's not addressed there, please let me know.

Closing this out for now

**Comment by xyznaveen** [comment]
Any updates on this issue ?
