### ISSUE TITLE
TrueTime incorrect on some devices due elapsedRealtime shifting

### ISSUE THREAD

**Issue by martinfilipekcz** [instacart/truetime-android#89]
Hello,
We are using non RX version of library. In application beta testing we encountered the problem that on some devices is TrueTime value shifted up to 2 minutes versus device time. So we started logging TrueTime information and device time and elapsedRealtime. Logs showed that calculated TrueTime is correct but the elapsedRealtime value jumps up and down so somethimes is showed time correct somethimes not. Do you know any solution for that?

**Comment by kaushikgopal** [comment]
hmm sorry I don't think I have any more insight into this. `SystemClock. elapsedRealtime` comes from the OS, so if those values are off, that can only point to maybe the quality of the device?

Have you noticed differences between device makes/models etc.?

Closing this out for now, but feel free to add more info.
