### ISSUE TITLE
put Log.x behind a configurable flag

### ISSUE THREAD

**Issue by kaushikgopal** [instacart/truetime-android#9]
this allows folks to put the logging behind a flag depending on environment etc.

courtesy: @Laimiux

**Comment by npace** [comment]
Great idea for the library, getting the _actual_ time on a mobile device can be a major pain...

Dunno if this is what you had in mind, but [here's a pull request](https://github.com/instacart/truetime-android/pull/16)

**Comment by kaushikgopal** [comment]
This is awesome, thanks.

I'll merge it in with the 1.6 release where i'm coupling a few more checks
and features. Added more useful logging there, so this would be especially
useful.

Much appreciated!

**Comment by npace** [comment]
Glad I helped!

**Comment by kaushikgopal** [comment]
closed with #16 

🙏 @npace
